# Generated by Django 4.0.6 on 2022-07-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('BuildingId', models.AutoField(primary_key=True, serialize=False)),
                ('BuildingName', models.CharField(max_length=100)),
                ('BuildingPhoto', models.CharField(max_length=100)),
                ('BuildingFloor', models.CharField(max_length=100)),
                ('BuildingFloorPhoto', models.CharField(max_length=100)),
                ('ApartmentNumb', models.CharField(max_length=100)),
                ('ApartmentPhoto', models.CharField(max_length=100)),
                ('ApartmentSurface', models.CharField(max_length=100)),
                ('ApartmentRooms', models.CharField(max_length=100)),
                ('ApartmentPrice', models.CharField(max_length=100)),
            ],
        ),
    ]
